### ISSUE TITLE
set BOT_TOKEN not working

### ISSUE THREAD

**Issue by Araraura** [oceanroleplay/discord.ts-example#27]
I'm not sure if this is the right place to ask about this issue, but I tried following the installation guide and using `set BOT_TOKEN=<your bot token>`, but after I use `npm run start` I get an error telling me that the token is invalid.

I tried wrapping my token in quotes or with arrows but I'm still getting the same error.

The only solution that worked for me was to paste my token directly inside the code, but of course that's far from ideal.

**Comment by oceanroleplay** [comment]
Did you used ``set BOT_TOKEN=<ABCD>`` format?

because if you did then it's wrong, it's ``set BOT_TOKEN=ABCD``

note: assuming you are a windows user.

**Comment by Araraura** [comment]
> Did you used `set BOT_TOKEN=<ABCD>` format?
> 
> because if you did then it's wrong, it's `set BOT_TOKEN=ABCD`
> 
> note: assuming you are a windows user.

Yea I tried pasting the token without wrapping it in anything - just directly after the equal sign. Same issue (should've mentioned that more clearly in the issue, my bad)

**Comment by oceanroleplay** [comment]
However this is not the issue of lib, it's depend on your environment, please see 

https://nodejs.dev/learn/how-to-read-environment-variables-from-nodejs

closing the issue with this reference.

**Comment by oceanroleplay** [comment]
seek more support on our discord server.
